### ISSUE TITLE
Error: Path contains invalid characters

### ISSUE THREAD

**Issue by SeaDude** [mrvautin/squido#2]
Hi there,

Instead of building from default blog, thought I'd try the `squido-docs` template. Getting similar errors when going this route. 

**Steps to repro:**

```
PS C:\Users\user7\Documents\portfolio> git clone https://github.com/mrvautin/squido-docs seanotes
Cloning into 'seanotes'...
remote: Enumerating objects: 660, done.
remote: Counting objects: 100% (660/660), done.
remote: Compressing objects: 100% (369/369), done.
Remote: Total 660 (delta 381), reused 513 (delta 236), pack-reused 0R
Receiving objects: 100% (660/660), 762.85 KiB | 2.26 MiB/s, done.
Resolving deltas: 100% (381/381), done.

PS C:\Users\user7\Documents\portfolio> cd .\seanotes\

PS C:\Users\user7\Documents\portfolio\seanotes> squido serve -b -w -c

Cleaned: C:\Users\user7\Documents\portfolio\seanotes\build
[Building environment: development]
Built: C:\Users\user7\Documents\portfolio\seanotes\build\getting-started\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\structure\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\usage-commands\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\configuration\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\posts\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\markdown\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\templates\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\sitemap-and-feeds\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\plugins\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\import-content\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\deployment-and-hosting\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\admin-editor\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\post-build-tasks\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\404.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\installation\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\getting-started\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\structure\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\usage\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\commands\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\config\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\configuration\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\posts\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\markdown\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\templates\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\themes\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\sitemap\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\rss\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\atom\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\json\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\plugins\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\import\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\ghost\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\wordpress\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\deployment\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\hosting\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\netlify\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\github\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\pages\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\aws\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\amplify\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\admin\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\editor\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\cms\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\build\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\git\index.html
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\package.json
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\robots.txt
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/favicon.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/netlify-build.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/netlify-color-accent.svg
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/netlify-environment.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/squido-admin.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/squido-social.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/squido.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/squido.svg
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/structure.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/javascripts/site.js
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\javascripts
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/stylesheets/style.css
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\stylesheets
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/stylesheets/syntax.css
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\stylesheets
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/github/create-repository-button.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images\github
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/github/create-repository-create.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images\github
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/github/create-repository-name.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images\github
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/github/create-repository-public-private.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images\github
Built: C:\Users\user7\Documents\portfolio\seanotes\build\sitemap.xml
Built: C:\Users\user7\Documents\portfolio\seanotes\build\rss
Built: C:\Users\user7\Documents\portfolio\seanotes\build\atom
Built: C:\Users\user7\Documents\portfolio\seanotes\build\json
[Build complete]
Failed to run plugin search.
Ex Error: ENOENT: no such file or directory, open 'C:\Users\user7\Documents\portfolio\seanotes\build\content\javascripts\searchdata.js'
[Watching for changes]
Server started at: http://localhost:4965
```

*Most* of the site appears, (missing favicon, logo, etc.), but curious why the `C:\Users\user7\Documents\portfolio\seanotes` path is duplicated in some of the file paths above. 

![image](https://user-images.githubusercontent.com/8636973/123038725-c601bf80-d3a5-11eb-9797-7ee2f3f0bb9f.png)

**Comment by mrvautin** [comment]
Thanks for reporting. I thought it was all cross platform but don't have a Windows computer to confirm. I've got one now to test and will fix the issue.

**Comment by mrvautin** [comment]
Fixed 6cad43d8487690603e61126476f5999ae29526b1.

**Comment by SeaDude** [comment]
Hi, Is there something I need to do other than `npm install -g squido` to pull in the fix? 

**I'm seeing the same issues:**

```
PS C:\Users\user7\Documents\portfolio> npm install -g squido

added 8 packages, removed 2 packages, changed 360 packages, and audited 369 packages in 23s

28 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\user7\Documents\portfolio> git clone https://github.com/mrvautin/squido-docs seanotes

Cloning into 'seanotes'...
remote: Enumerating objects: 660, done.
remote: Counting objects: 100% (660/660), done.
remote: Compressing objects: 100% (369/369), done.
Receiving objects:  98% (647/660)used 513 (delta 236), pack-reused 0
Receiving objects: 100% (660/660), 762.85 KiB | 1.97 MiB/s, done.
Resolving deltas: 100% (381/381), done.
PS C:\Users\user7\Documents\portfolio> cd .\seanotes\
PS C:\Users\user7\Documents\portfolio\seanotes> squido serve -b -w -c
Cleaned: C:\Users\user7\Documents\portfolio\seanotes\build
[Building environment: development]
Built: C:\Users\user7\Documents\portfolio\seanotes\build\getting-started\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\structure\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\usage-commands\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\configuration\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\posts\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\markdown\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\templates\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\sitemap-and-feeds\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\plugins\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\import-content\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\deployment-and-hosting\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\admin-editor\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\post-build-tasks\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\404.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\installation\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\getting-started\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\structure\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\usage\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\commands\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\config\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\configuration\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\posts\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\markdown\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\templates\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\themes\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\sitemap\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\rss\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\atom\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\json\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\plugins\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\import\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\ghost\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\wordpress\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\deployment\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\hosting\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\netlify\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\github\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\pages\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\aws\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\amplify\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\admin\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\editor\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\cms\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\build\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\git\index.html
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\package.json
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\robots.txt
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/favicon.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/netlify-build.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/netlify-color-accent.svg
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/netlify-environment.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/squido-admin.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/squido-social.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/squido.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/squido.svg
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/structure.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/javascripts/site.js
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\javascripts
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/stylesheets/style.css
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\stylesheets
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/stylesheets/syntax.css
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\stylesheets
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/github/create-repository-button.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images\github
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/github/create-repository-create.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images\github
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/github/create-repository-name.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images\github
Error trying to copy contents on file: C:/Users/user7/Documents/portfolio/seanotes/source/content/images/github/create-repository-public-private.png
Error: Path contains invalid characters: C:\Users\user7\Documents\portfolio\seanotes\build\C:\Users\user7\Documents\portfolio\seanotes\source\content\images\github
Built: C:\Users\user7\Documents\portfolio\seanotes\build\sitemap.xml
Built: C:\Users\user7\Documents\portfolio\seanotes\build\rss
Built: C:\Users\user7\Documents\portfolio\seanotes\build\atom
Built: C:\Users\user7\Documents\portfolio\seanotes\build\json
[Build complete]
Failed to run plugin search.
Ex Error: ENOENT: no such file or directory, open 'C:\Users\user7\Documents\portfolio\seanotes\build\content\javascripts\searchdata.js'
[Watching for changes]
Server started at: http://localhost:4965
```

![image](https://user-images.githubusercontent.com/8636973/123354575-d0909600-d518-11eb-9052-55d3c6f97321.png)

**Comment by mrvautin** [comment]
@SeaDude. New code is not on NPM yet, you can grab the new code easily with: `npm i -g https://github.com/mrvautin/squido`

**Comment by SeaDude** [comment]
Right on. Thanks for the details. 

Can you see what I'm missing?

```
PS C:\Users\user7\Documents\portfolio> rm .\seanotes\ -r -fo

PS C:\Users\user7\Documents\portfolio> npm uninstall squido

up to date, audited 1 package in 727ms

found 0 vulnerabilities

PS C:\Users\user7\Documents\portfolio> npm install -g https://github.com/mrvautin/squido

changed 368 packages, and audited 369 packages in 51s

28 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

PS C:\Users\user7\Documents\portfolio> git clone https://github.com/mrvautin/squido-docs seanotes
Cloning into 'seanotes'...
remote: Enumerating objects: 660, done.
remote: Counting objects: 100% (660/660), done.
Remote: Compressing objects: 100% (369/369), done.
Receiving objects:  98% (647/660)used 513 (delta 236), pack-reused 0 eceiving objects:  96% (634/660)
Receiving objects: 100% (660/660), 762.85 KiB | 1.91 MiB/s, done.
Resolving deltas: 100% (381/381), done.

PS C:\Users\user7\Documents\portfolio> cd .\seanotes\

PS C:\Users\user7\Documents\portfolio\seanotes> squido serve -b -w -c
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\user7\AppData\Roaming\npm\node_modules\squido\cli.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
PS C:\Users\user7\Documents\portfolio\seanotes> ls


    Directory: C:\Users\user7\Documents\portfolio\seanotes


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         6/24/2021   6:24 PM                source
-a----         6/24/2021   6:24 PM             19 .gitignore
-a----         6/24/2021   6:24 PM           1706 config.js
-a----         6/24/2021   6:24 PM          82396 package-lock.json
-a----         6/24/2021   6:24 PM            214 package.json
-a----         6/24/2021   6:24 PM            238 README.md
```

**Comment by SeaDude** [comment]
When I install directly from this repo, I get the error:

```
PS C:\Users\user7\Documents\portfolio\seanotes> squido serve -b -w -c
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\user7\AppData\Roaming\npm\node_modules\squido\cli.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
```

If I run `npm uninstall -g https://github.com/mrvautin/squido` then `npm install -g squido`, I don't get the above error, but the original error in this issue is present.

**Comment by mrvautin** [comment]
Hi @SeaDude, thats unusual. It seems Windows needs the `.git` on the end of the URL. Eg: `npm install -g https://github.com/mrvautin/squido.git`. Can you try with this command?

**Comment by SeaDude** [comment]
Bingo! 

Thank you for the timely follow through. I'm really excited to use the tool. I've made my way through many SSG's over the years (Gitbook, Jekyll, Hugo, Gatsby and DocFX) but never settled on one for some reason or another. 

So far, Squido seems dead simple to setup and customize. 

Take care!

---

**Results:**

```
PS C:\Users\user7\Documents\portfolio> npm install -g https://github.com/mrvautin/squido.git
C:\Users\user7\AppData\Roaming\npm\squido -> C:\Users\user7\AppData\Roaming\npm\node_modules\squido\cli.js

> esbuild@0.11.10 postinstall C:\Users\user7\AppData\Roaming\npm\node_modules\squido\node_modules\esbuild
> node install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\squido\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ squido@1.0.16
added 362 packages from 327 contributors in 33.387s
PS C:\Users\user7\Documents\portfolio> git clone https://github.com/mrvautin/squido-docs seanotes; cd seanotes
Cloning into 'seanotes'...
remote: Enumerating objects: 660, done.
remote: Counting objects: 100% (660/660), done.
remote: Compressing objects: 100% (369/369), done.
Receiving objects:  98% (647/660)used 513 (delta 236), pack-reused 0 eceiving objects:  96% (634/660)
Receiving objects: 100% (660/660), 762.85 KiB | 2.13 MiB/s, done.
Resolving deltas: 100% (381/381), done.
PS C:\Users\user7\Documents\portfolio\seanotes> squido serve -b -w -c
Cleaned: C:\Users\user7\Documents\portfolio\seanotes\build
[Building environment: development]
Built: C:\Users\user7\Documents\portfolio\seanotes\build\getting-started\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\structure\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\usage-commands\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\configuration\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\posts\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\markdown\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\templates\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\sitemap-and-feeds\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\plugins\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\import-content\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\deployment-and-hosting\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\admin-editor\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\post-build-tasks\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\404.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\installation\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\getting-started\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\structure\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\usage\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\commands\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\config\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\configuration\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\posts\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\markdown\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\templates\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\themes\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\sitemap\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\rss\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\atom\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\json\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\plugins\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\import\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\ghost\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\wordpress\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\deployment\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\hosting\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\netlify\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\github\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\pages\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\aws\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\amplify\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\admin\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\editor\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\cms\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\build\index.html
Built: C:\Users\user7\Documents\portfolio\seanotes\build\tag\git\index.html
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\package.json
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\robots.txt
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\images\favicon.png
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\images\netlify-build.png
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\images\netlify-color-accent.svg
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\images\netlify-environment.png
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\images\squido-admin.png
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\images\squido-social.png
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\images\squido.png
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\images\squido.svg
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\images\structure.png
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\javascripts\site.js
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\stylesheets\style.css
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\stylesheets\syntax.css
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\images\github\create-repository-button.png
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\images\github\create-repository-create.png
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\images\github\create-repository-name.png
Copied: C:\Users\user7\Documents\portfolio\seanotes\build\content\images\github\create-repository-public-private.png
Minified: C:\Users\user7\Documents\portfolio\seanotes\build\content\javascripts\site.min.js
Minified: C:\Users\user7\Documents\portfolio\seanotes\build\content\stylesheets\style.min.css
Minified: C:\Users\user7\Documents\portfolio\seanotes\build\content\stylesheets\syntax.min.css
Built: C:\Users\user7\Documents\portfolio\seanotes\build\sitemap.xml
Built: C:\Users\user7\Documents\portfolio\seanotes\build\rss
Built: C:\Users\user7\Documents\portfolio\seanotes\build\atom
Built: C:\Users\user7\Documents\portfolio\seanotes\build\json
[Build complete]
[Watching for changes]
Server started at: http://localhost:4965
```
